# Generated by Django 5.1.7 on 2025-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('ri-sword-fill', 'Sword (Mythic+)'), ('ri-trophy-fill', 'Trophy (Raid)'), ('ri-shield-star-fill', 'Shield (PvP)'), ('ri-bar-chart-fill', 'Chart (Leveling)'), ('ri-treasure-map-fill', 'Treasure (Mounts)'), ('ri-coins-fill', 'Coins (Gold)')], max_length=50)),
                ('modal_id', models.SlugField(help_text="Used for the modal ID (e.g., 'mythicModal')", unique=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which services appear')),
                ('modal_title', models.CharField(max_length=100)),
                ('modal_description', models.TextField()),
                ('modal_features', models.TextField(help_text='One feature per line')),
                ('modal_pricing_left', models.TextField(help_text='Pricing left column (One item per line)')),
                ('modal_pricing_right', models.TextField(help_text='Pricing right column (One item per line)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
