# Generated by Django 5.1.7 on 2025-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_left',
            field=models.CharField(default='pricing :', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='title_right',
            field=models.CharField(default='pricing :', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='title_top',
            field=models.CharField(default='features :', max_length=100),
        ),
    ]
