# Generated by Django 5.1.7 on 2025-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service_title_left_service_title_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
